#source 'https://gitlab.btpoc.com/app/ios/componentrepo.git'   # 私有库
source 'https://github.com/CocoaPods/Specs.git'  # 官方库

use_frameworks!
use_modular_headers!

target 'YHLCore_Example' do
  pod 'YHLCore', :path => '../'

end
