# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'fileutils'

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :update do |options|

tagNum = options[:version]

	current_dir = File.dirname(File.expand_path(__FILE__))
        
        curpath = File.expand_path("../..", current_dir)

	Dir.chdir(curpath)

	`git stash save "yanghl_temp"`

	podspecName = podspec_name

	path = curpath+"/#{podspecName}.podspec"

	 return unless File.exists? path


lines = IO.readlines(path).map do |line|
    if line.include? "s.version          ="
      
      line = "    s.version          = '#{tagNum}'"
    else

      line
    end
    end
      File.open(path, 'w') do |file|
      file.puts lines 
  end


`git add .`

`git commit -m "发版" .`

`git push`


if git_tag_exists(tag: tagNum)
remove_git_tag(tagNum: tagNum)
end

add_git_tag(
  tag: tagNum
)

push_git_tags


	`git stash pop stash@{0}`


#移动podspec文件

repoPath = File.expand_path("../..", current_dir)+"/seanRepo/YHLCore/"+tagNum


Dir.mkdir(repoPath)
FileUtils.cp(path , repoPath)

Dir.chdir(File.expand_path("../..", current_dir)+"/seanRepo")
	

`git add .`

`git commit -m "发版" .`

`git push`

	puts "==========#{repoPath}"

	


  end
end


def podspec_name 
  podspecName = File.basename(File.expand_path(Dir.pwd), Dir.getwd)
  Dir.children("..").each{|x| 
    fileName = x.sub!(/\..*/,"")
    if podspecName.casecmp? fileName
      podspecName = fileName
    end
  }
  podspecName
end
